name: Build and Deploy Lambda

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     lambda:
    #       - name: api-gateway-authorizer
    #         function_name: api-gatway-authorizer
    #       - name: rds-lambda
    #         function_name: rds-lambda

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Zip Authorizer Lambda
        run: |
          cd dist/api-gateway-authorizer
          zip -r ../../api-gateway-authorizer.zip .

      - name: Zip RDS Lambda
        run: |
          cd dist/rds-lambda
          zip -r ../../rds-lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy Authorizer Lambda
        run: |
          aws lambda update-function-code \
            --function-name api-gateway-authorizer \
            --zip-file fileb://api-gateway-authorizer.zip

      - name: Deploy RDS Lambda
        run: |
          aws lambda update-function-code \
            --function-name rds-lambda \
            --zip-file fileb://rds-lambda.zip
